line-length = 100
target-version = "py38"

[lint]
select = [
    "A",    # flake8-builtins
    "ANN", # flake8-annotations
    "ARG",  # flake8-unused-arguments
    "B",    # Bugbear
    "C",
    "COM", # flake8-commas
    "C4",   # flake8-comprehensions
    "DTZ",  # flake8-datetimez
#    "D",    # pydocstyle, TODO: activate
    "E",    # pycodestyle errors
    "ERA",  # eradicate commented out code
    "F",    # pyflakes
    "FLY",  # flynt
    "G",    # flake8-logging-format
    "I",    # incomplete isort
    "INP",  # flake8-no-pep420
    "LOG",  # flake8-logging
    "N",    # naming
    "NPY",  # NumPy-specific rules
    "PD",   # pandas-vet
    "PERF", # Perflint
    "PL",   # Pylint
    "PTH",  # flake8-use-pathlib
    "PYI",  # flake8-pyi
    "RET",  # flake8-return
    "RUF",  # Ruff-specific rules
    "S",    # bandit, security
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
    "YTT",  # flake8-2020
]
ignore = [
    "N802", "N803", "N806", "N815", "N816", # naming (si-units should stay)
    "PLR2004", # magic values
    "TID252", # relative imports from parent
    "PLR0904", # complexity
    "PLR0911", "PLR0912", # complexity
    "PLR0913", "PLR0915", # complexity
    "C901", # complexity
    "E203", # whitespace before ':' (black-default)
    "ANN101", "ANN102", # self & cls not type-annotated
    "ANN401",  # Any as valid type
    "COM812", # trailing comma, same line
    "PYI041", # int != float
    "ERA001", # commented out code
    "E501", # line too long
]

exclude= [  # external projects
    "software/shepherd-datalib/*",
    "software/shepherd-webservice/*",
    "software/firmware/pru0-cython-module/*",
]

[lint.per-file-ignores]
"*/tests/**" = ["ARG", "S", "D"]
"*/examples/**" = ["INP001"]  # no namespace

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[lint.isort]
force-single-line = true

[lint.pyupgrade]
keep-runtime-typing = true

[format] # per default like Black
